ERROR_CODES = {
    'PROPERTY_NOT_FOUND': 'PROPERTY_NOT_FOUND',
    'BOOKING_CONFLICT': 'BOOKING_CONFLICT',
    'REPAIR_INVALID': 'REPAIR_INVALID',

    # 报修工单
    'REPAIR_NOT_FOUND': 'REPAIR_NOT_FOUND',
    'REPAIR_FAULT_TYPE_INVALID': 'REPAIR_FAULT_TYPE_INVALID',
    'REPAIR_DESCRIPTION_EMPTY': 'REPAIR_DESCRIPTION_EMPTY',
    'REPAIR_NOT_ACCEPTABLE': 'REPAIR_NOT_ACCEPTABLE',
    'REPAIR_NOT_PROCESSABLE': 'REPAIR_NOT_PROCESSABLE',
    'REPAIR_TRANSFER_PENDING': 'REPAIR_TRANSFER_PENDING',

    # 物业人员
    'STAFF_NOT_FOUND': 'STAFF_NOT_FOUND',
    'STAFF_REQUIRED': 'STAFF_REQUIRED',
    'STAFF_FORBIDDEN': 'STAFF_FORBIDDEN',

    # 转派
    'TRANSFER_NOT_FOUND': 'TRANSFER_NOT_FOUND',
    'TRANSFER_TARGET_SAME_AS_HANDLER': 'TRANSFER_TARGET_SAME_AS_HANDLER',
    'TRANSFER_REASON_EMPTY': 'TRANSFER_REASON_EMPTY',
    'TRANSFER_NOT_PENDING': 'TRANSFER_NOT_PENDING',
}

ERROR_MESSAGES = {
    'REPAIR_NOT_FOUND': '报修工单不存在',
    'REPAIR_FAULT_TYPE_INVALID': '故障类型不合法',
    'REPAIR_DESCRIPTION_EMPTY': '故障描述不能为空',
    'REPAIR_NOT_ACCEPTABLE': '当前工单状态不可接单',
    'REPAIR_NOT_PROCESSABLE': '当前工单不可执行该操作',
    'REPAIR_TRANSFER_PENDING': '工单存在待接受的转派，原处理人暂不能处理或再次转派',
    'STAFF_NOT_FOUND': '物业人员不存在',
    'STAFF_REQUIRED': '缺少操作人员（staffId）',
    'STAFF_FORBIDDEN': '当前物业人员无权操作该工单',
    'TRANSFER_NOT_FOUND': '转派记录不存在',
    'TRANSFER_TARGET_SAME_AS_HANDLER': '转派目标不能是当前处理人本人',
    'TRANSFER_REASON_EMPTY': '转派原因不能为空',
    'TRANSFER_NOT_PENDING': '该转派已被处理，不能重复接受或拒绝',
}
